using System;
using System.IO;
using System.Reflection;

namespace LWSwnS.Diagnostic
{
    public enum MessageType
    {
        Normal, Warning, Error
    }
    public interface IDebugger
    {
        void Log(string msg);
        void Log(string msg, MessageType msgType);
    }
    public class EmptyDebugger : IDebugger
    {
        public void Log(string msg)
        {
            System.Diagnostics.StackTrace stack = new System.Diagnostics.StackTrace(true);
            var f = stack.GetFrame(1);
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write((new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name);
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("][");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("NORAML ");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("]");
            Console.WriteLine(msg);
        }

        public void Log(string msg, MessageType msgType)
        {
            System.Diagnostics.StackTrace stack = new System.Diagnostics.StackTrace(true);
            var f = stack.GetFrame(1);
            string CombinedMsg = $"[{(new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name}]";
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write((new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name);
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("][");
            switch (msgType)
            {
                case MessageType.Normal:
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.Write("NORAML ");
                    Console.ForegroundColor = ConsoleColor.White;
                    break;
                case MessageType.Warning:
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.Write("WARNING");
                    Console.ForegroundColor = ConsoleColor.White;
                    break;
                case MessageType.Error:
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.Write("ERROR  ");
                    Console.ForegroundColor = ConsoleColor.White;
                    break;
                default:
                    break;
            }
            Console.Write("]");
            Console.WriteLine(msg);
        }
    }
    public class Debugger : IDebugger
    {
        public static IDebugger currentDebugger;
        int LogLevel = 0;
        int LimitSize = 512;
        string fileName = "";
        public Debugger(int Level, int Size)
        {
            LimitSize = Size;
            LogLevel = Level;
            var Now = DateTime.Now;
            if (!Directory.Exists("./Log"))
            {
                Directory.CreateDirectory("./Log");
            }
            fileName = $"./Log/{Now.Year}-{Now.Month}-{Now.Day}.{Now.Hour}-{Now.Minute}-{Now.Second}.log";
            File.Create(fileName).Close();
            File.WriteAllText(fileName, "[LWSwnS Log]");
            File.AppendAllText(fileName, "\r\nGenerated by LWSwnS.Diagnostic");
        }
        public void Log(string msg)
        {
            System.Diagnostics.StackTrace stack = new System.Diagnostics.StackTrace(true);
            var f = stack.GetFrame(1);
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            try
            {
                Console.Write((new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name);
            }
            catch (Exception)
            {
                Console.Write("CODE_SCRIPT");
            }
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("][");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("NORAML ");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("]");
            Console.WriteLine(msg);
            string CombinedMsg;
            try
            {

                CombinedMsg = $"[{(new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name}][NORMAL ]{msg}";
            }
            catch (Exception)
            {

                CombinedMsg = $"[CODE_SCRIPT][NORMAL ]{msg}";
            }
            if (LogLevel == 0)
            {

                File.AppendAllText(fileName, "\r\n" + CombinedMsg);
                FileSizeLimitDetect();
            }
        }
        public void FileSizeLimitDetect()
        {
            var oldf = new FileInfo(fileName);
            if (oldf.Length / 1024 > LimitSize)
            {
                var Now = DateTime.Now;
                fileName = $"./Log/{Now.Year}-{Now.Month}-{Now.Day}.{Now.Hour}-{Now.Minute}-{Now.Second}.log";
                File.Create(fileName).Close();
                File.WriteAllText(fileName, "[LWSwnS Log]");
                File.AppendAllText(fileName, "\r\nGenerated by LWSwnS.Diagnostic");
            }
        }
        public void Log(string msg, MessageType msgType)
        {
            System.Diagnostics.StackTrace stack = new System.Diagnostics.StackTrace(true);
            var f = stack.GetFrame(1);
            string CombinedMsg;
            Console.Write("[");
            Console.ForegroundColor = ConsoleColor.Green;
            try
            {
                CombinedMsg= $"[{(new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name}]";
                Console.Write((new FileInfo(Assembly.GetAssembly(f.GetMethod().DeclaringType).Location)).Name);
            }
            catch (Exception)
            {
                Console.Write("CODE_SCRIPT");
                CombinedMsg = $"[CODE_SCRIPT]";
            }
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("][");
            bool willLog = true;
            switch (msgType)
            {
                case MessageType.Normal:
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.Write("NORAML ");
                    if (LogLevel != 0)
                    {
                        willLog = false;
                    }
                    CombinedMsg += "[NORMAL ]";
                    Console.ForegroundColor = ConsoleColor.White;
                    break;
                case MessageType.Warning:
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.Write("WARNING");
                    CombinedMsg += "[WARNING]";
                    if (LogLevel == 2) willLog = false;
                    Console.ForegroundColor = ConsoleColor.White;
                    break;
                case MessageType.Error:
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.Write("ERROR  ");
                    CombinedMsg += "[ERROR  ]";
                    Console.ForegroundColor = ConsoleColor.White;
                    break;
                default:
                    break;
            }
            CombinedMsg += msg;
            Console.Write("]");
            Console.WriteLine(msg);
            if (willLog == true)
            {
                File.AppendAllText(fileName, "\r\n" + CombinedMsg);
                FileSizeLimitDetect();
            }
        }
    }
}
