name: .NET Core in Ubuntu
on: 
# on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: |
        cd LWSwnS
        dotnet build --configuration Release
    - uses: actions/upload-artifact@v1
      with:
        name: LWSwnS-Package
        path: LWSwnS\LWSwnS\bin\Release\
