name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '5.0.0-preview.6'
    - name: Build with dotnet
      run: |
        cd LWSwnS
        dotnet build --configuration Release
    - uses: actions/upload-artifact@v1
      with:
        name: LWSwnS-Package
        path: LWSwnS\LWSwnS\bin\Release\
